project_id = "cbfqwaqwliehgxsdueem"

[functions.fetch-spotify-tracks]
verify_jwt = false

[functions.search-spotify-music]
verify_jwt = false

[functions.spotify-oauth-callback]
verify_jwt = false

[functions.get-user-spotify-playlists]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = false
